### ISSUE TITLE
 Basic Form Design Lacks Visual Appeal

### ISSUE THREAD

**Issue by TornovDutta** [Code-Social/official-website#101]
# Description:
The current "Add Event" form looks very basic and lacks visual appeal. The design is too plain, with no distinct styling or hierarchy to guide the user’s eye. The date picker and input fields have minimal contrast and do not stand out. The button lacks a hover effect or active state, making it feel less interactive. Additionally, there’s no padding or spacing to create a balanced layout. Enhancing colors, adding borders or shadows, and incorporating hover effects would significantly improve the form's usability and aesthetic.

### sceenshot:
![Screenshot 2024-10-09 020048](https://github.com/user-attachments/assets/b5320c22-2c96-4e6f-adca-2eb0d4d8767c)

**Comment by TornovDutta** [comment]
@arushi2610 please label the issuse

**Comment by TornovDutta** [comment]
@arushi2610 please assign the issuse to me

**Comment by SaurabhS55** [comment]
@TornovDutta I have assigned this issue. You can start working on it

**Comment by TornovDutta** [comment]
@SaurabhS55 please level the issuse
