### ISSUE TITLE
The current website interface could be improved for better user experience and ease of navigation.

### ISSUE THREAD

**Issue by yogeswari05** [Code-Social/official-website#11]
The current interface could use some improvements to enhance user experience. We could consider using a front-end framework like React for a cleaner, more dynamic design. Alternatively, we can use tools such as Bootstrap or Tailwind CSS for responsive layout.
I want to contribute to this.

**Comment by SaurabhS55** [comment]
Currently, we will not be using react. We will only be using html,css and js.

**Comment by SaurabhS55** [comment]
You can find out more features to work on
