### ISSUE TITLE
ADD A LOGIN PAGE 

### ISSUE THREAD

**Issue by HS202022** [Code-Social/official-website#137]
**Is your feature request related to a problem? Please describe.**
ADDITION OF A LOGIN PAGE FOR GOOD USER EXPERIENCE

**Describe the solution you'd like**
JUST WANT TO ADD A LOGIN PAGE

sample
https://github.com/user-attachments/assets/f6a8e292-2ed1-42aa-a7aa-b517be7a9d2a

**Comment by ChampGupta** [comment]
I will add login page please assign it to me under gssoc-ext and hactoberfest-accepted labels.
