### ISSUE TITLE
Mouse Cursor Trail Effect

### ISSUE THREAD

**Issue by Priyanshi0112** [Code-Social/official-website#157]
The mouse cursor trail effect is a visual effect that creates a trail of light behind the mouse cursor as it moves across the screen.

 The effect is achieved by creating a custom cursor element and using CSS to style it with a neon-like glow. JavaScript is used to track the mouse movement and update the cursor's position accordingly.

Details:

1. The cursor trail effect is created using a combination of HTML, CSS, and JavaScript.
2. The HTML structure consists of a container element and a cursor element.
3. The CSS styles are used to create the neon-like glow effect and position the cursor element.
4. The JavaScript code tracks the mouse movement and updates the cursor's position accordingly.
5. The effect can be customized by adjusting the CSS styles and JavaScript code.

Please assign this issue to me under GSSoC- ext and Hacktoberfest 

Thank You

**Comment by arushi2610** [comment]
Thank you for your suggestion, this feature isn't required.
