### ISSUE TITLE
Text color not visible

### ISSUE THREAD

**Issue by Kajalmehta29** [Code-Social/official-website#170]
<img width="493" alt="Screenshot 2024-10-12 at 5 09 12 PM" src="https://github.com/user-attachments/assets/fb5207f9-4676-4689-b07a-6f88e21e3774">

Due to color of links, text is not visible.I want to fix this issue.
Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by arushi2610** [comment]
Raise a PR when you're done.
