### ISSUE TITLE
Volunteer Opportunities Link Not Redirecting to Webpage

### ISSUE THREAD

**Issue by Nitheesha33** [Code-Social/official-website#177]
**Describe the bug**
The "Volunteer Opportunities" link in the footer of the Code Social Community website is not functioning as expected. When clicked, it does not redirect the user to any page or provide relevant content.

**To Reproduce**
1)Go to the Code Social Community website.
2)Scroll down to the footer.
3)Click on the "Volunteer Opportunities" link.
4)Observe that the link does not lead to any page or display relevant information.

**Expected behavior**
The "Volunteer Opportunities" link should redirect to a dedicated webpage outlining guidelines for volunteers, responsibilities, code of conduct, and providing a form for interested applicants to apply for volunteer roles. This webpage should serve as a resource for those interested in contributing to the community.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 129.0.6668.100 (Official Build) (64-bit)

**Additional context**
I propose developing a new "Volunteer Opportunities" webpage to resolve this issue. This page will include detailed guidelines, responsibilities, and a code of conduct for volunteers, along with a form to collect necessary information from volunteer applicants. Additional content may be added to ensure the webpage is informative and engaging for potential volunteers.

@pulkitpathak99 please assign me this issue I would love to work on this. And I also request to add relevant "gssoc-ext" labels

**Comment by Rizwan102003** [comment]
I am assigning this issue. @pulkitpathak99 @SaurabhS55  please put the appropriate labels.

**Comment by tobiasrahul** [comment]
@Rizwan102003 Hey Please assign this to me as I have a good experience in web development as I worked as an intern at Metacrafters.
