### ISSUE TITLE
Create Learn section

### ISSUE THREAD

**Issue by pavitraag** [Code-Social/official-website#18]
I would like to create a learn section where they can learn different courses.Please assign me under gssoc.

**Comment by SaurabhS55** [comment]
@pavitraag I have assigned this issue to you. You can start working on this issue.

**Comment by gaurkrutika** [comment]
I want to contribute to this project. Please assign it to me

**Comment by SaurabhS55** [comment]
@pavitraag are you working on this?

**Comment by pavitraag** [comment]
Yes @SaurabhS55 I am working on it ,  i will raise pr by tomorrow night
