### ISSUE TITLE
Issues with Event Calendar

### ISSUE THREAD

**Issue by TornovDutta** [Code-Social/official-website#185]
# About:
<ol>
<li>Unreadable Title: The "Event Calendar" heading is difficult to read due to poor contrast.

<li>Event Titles Cut Off: Event names like "React Workshop" are truncated, making them hard to understand.

<li>Inconsistent Design: Some events have colored backgrounds, while others do not, creating a lack of visual harmony.

<li>Poor Layout: The "Add Event" section feels disconnected from the calendar, with misaligned elements.

<li>Cluttered Appearance: The lack of spacing and inconsistent color scheme make the calendar hard to navigate and visually unappealing.
</ol>

### sceenshot:
![Screenshot 2024-10-13 010636](https://github.com/user-attachments/assets/d7ecb514-28ee-4724-96ec-56bf19160332)

**Comment by TornovDutta** [comment]
@SaurabhS55 please label the issuse and assign it to me

**Comment by arushi2610** [comment]
Please raise a PR when you're done.

**Comment by TornovDutta** [comment]
@arushi2610, you've closed the issue. Can I still raise a PR now? Why did you close the issue after giving permission to raise a PR on it?
