### ISSUE TITLE
Adding ContactUs with complete functionality

### ISSUE THREAD

**Issue by Bhum-ika** [Code-Social/official-website#186]
**Is your feature request related to a problem? Please describe.**
Contact us link is provided but there is no page.

**Describe the solution you'd like**
I will create a contact us form and will use email.js for its backend logic.

**Additional context**
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by arushi2610** [comment]
A page is created but I think it wasn't linked. Kindly work on backend logic.  Please raise a PR when you're done.

**Comment by Bhum-ika** [comment]
The logic is done and you have closed it then how should I  proceed.
