### ISSUE TITLE
calender is setting event for all years with same month and day.

### ISSUE THREAD

**Issue by vashujoshi** [Code-Social/official-website#187]
When setting an event in the calendar, the event is scheduled not only for the current year but also for every year that has the same month and date.

Go to the calendar application.
Create a new event and set it for a specific date and time.
Save the event.
Observe that the event is scheduled not just for the selected year but also for future years on the same month and day.

**Expected behavior**
The event should be set only for the current year unless specified as a recurring event.

![rep1](https://github.com/user-attachments/assets/b8a12b79-4a8a-43b0-a436-38bac07d61fc)

![rep2](https://github.com/user-attachments/assets/fb5afaf4-da3f-42c9-97c0-aea75a60caa1)

**Comment by vashujoshi** [comment]
I have solved the issue plz label this as gssoc extend ,hactoberfest,level 3 
and assign me this issue.
![calen](https://github.com/user-attachments/assets/552f7b00-7b0b-48e7-ac85-6be7f7a572c1)
![calen1](https://github.com/user-attachments/assets/7a3693a6-a3b3-4aed-85b1-61dc7af13fe9)

**Comment by arushi2610** [comment]
@SaurabhS55 @pulkitpathak99 I'm assigning the issue, kindly add the level label.

**Comment by vashujoshi** [comment]
thx @arushi2610

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...
