### ISSUE TITLE
Navigation Bar UI

### ISSUE THREAD

**Issue by aarch34** [Code-Social/official-website#194]
![Screenshot 2024-10-13 193104](https://github.com/user-attachments/assets/40ce0bbb-c311-4ba2-a7fd-473dacb83a3d)

I can make a better looking navbar which looks aesthetically pleasing with better UI.
Please assign me this issue and I can work on it.
@arushi2610

**Comment by RAMIREDDYGAYATHRI02** [comment]
@sanjay-kv can you please label it i will start working on it!
