### ISSUE TITLE
About section styling improvment 

### ISSUE THREAD

**Issue by aarch34** [Code-Social/official-website#196]
![image](https://github.com/user-attachments/assets/2c1ef43e-0dd1-48ff-9f61-eb6d9ddc5e68)

I can improve the styling of the about section and make it look better.
Please assign me this issue, i would like to work on it.
@arushi2610 
@Rizwan102003

**Comment by naitikhoriya1** [comment]
Hi https://github.comgauravsingh1281,

I’d like to take up this task: About section styling improvment #196
I’m confident I can complete it and contribute to the project.

Could you please assign it to me? I’ll make sure to deliver by the deadline and follow the project’s guidelines closely. If there are any specific requirements or preferences, feel free to let me know.

Looking forward to your approval!

Thanks,
@naitikhoriya1

**Comment by Rizwan102003** [comment]
@aarch34 I have assigned you the issue. @SaurabhS55 @pulkitpathak99 please put the labels here. @naitikhoriya1 we will be assigning the issues on a first come first serve basis. If @aarch34 wants to collaborate with you then we can allow it,otherwise not.

**Comment by aarch34** [comment]
Thank you
