### ISSUE TITLE
FEAT: Assign me this task of completing the mentorship section

### ISSUE THREAD

**Issue by vashujoshi** [Code-Social/official-website#210]
I’m always frustrated when I visit the website and there is no dedicated section that introduces our mentors. Users who are interested in learning or mentorship opportunities may want to know more about the people they will be learning from.

I would like to **add a “Mentors” section** where users can view different mentors in a card format. Each card will display a mentor's image, a brief description of their expertise, and have a hover effect that adds interactivity. This section will help users easily identify who the mentors are, along with a small intro about each mentor.
I considered simply adding a text-based list of mentors, but it wouldn’t be as engaging or visually appealing. **Cards with hover effects** will be more interactive and provide a better user experience. Another alternative is to show only names with links to full mentor profiles, but it lacks immediate information on the landing page.

In the mentor section, there will be a list of cards for each mentor. Each card will have an image of the mentor, their name, and a brief description of their expertise. The hover effect will highlight the card and could display additional information like contact links (LinkedIn or email). A responsive design should ensure the section looks good on all device size

**ASSIGN ME THIS UNDER HACKTOBERFEST OPENED, GSSOC EXTENDED ,LEVEL 3**

![2024-10-14 (3)](https://github.com/user-attachments/assets/c8a6d54f-70e2-45bf-bdeb-77d45931b6a8)

![MEN](https://github.com/user-attachments/assets/61278a52-914e-4110-b945-9c59e9c26c80)

**Comment by vashujoshi** [comment]
@arushi2610 @pulkitpathak99 @SaurabhS55

**Comment by Rizwan102003** [comment]
I have assigned this issue to you @vashujoshi . Please make sure to use a separate html file for the mentorship page so that it isn't a section in the homepage but rather redirects from the homepage to a separate page. For any queries,feel free to contact us through the discord link in Readme.md . @SaurabhS55 @pulkitpathak99 please put the appropriate gssoc tags.

**Comment by SaurabhS55** [comment]
@vashujoshi start working on it. 
And make sure to create new branch for your changes.

**Comment by vashujoshi** [comment]
Thx for assigning the task would try my best to complete it as soon as possible.
