### ISSUE TITLE
Solve Images not loading issue

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Code-Social/official-website#222]
These three images(website logo, dark mode & light mode icon image) are not loading in Header, which doesn't look good.

I want to Fixed this issue properly. PA please assign me this task.

![Screenshot 2024-10-14 191044](https://github.com/user-attachments/assets/a36cf339-56a6-4987-8b7c-dec9262ca430)

**Comment by Subhajit-2023-44** [comment]
@SaurabhS55 @pulkitpathak99 @Rizwan102003 PA please assign me

**Comment by pulkitpathak99** [comment]
I have assigned this issue to you @Subhajit-2023-44 !
