### ISSUE TITLE
Adding a sign up and login page

### ISSUE THREAD

**Issue by sayanp607** [Code-Social/official-website#230]
**Is your feature request related to a problem? Please describe.**
Adding a sign up and login page will increase the quality of the website. As well as , it will be very good for user experience and authentication.

**Describe the solution you'd like**
Please assign this task to me. I have developed these features many times earlier and have quite experience.

**Comment by naitikhoriya1** [comment]
Hi https://github.comgauravsingh1281,

I’d like to take up this task: Adding a sign up and login page #230
I’m confident I can complete it and contribute to the project.

Could you please assign it to me? I’ll make sure to deliver by the deadline and follow the project’s guidelines closely. If there are any specific requirements or preferences, feel free to let me know.

Looking forward to your approval!

Thanks,
@naitikhoriya1

**Comment by Rizwan102003** [comment]
We currently do not need auth page for your website as we do not store any personal info.you can think of some other issues guys. Happy contributing...
