### ISSUE TITLE
Issue: Footer Alignment, Extra Space, and Logo Misalignment

### ISSUE THREAD

**Issue by MadhavDhatrak** [Code-Social/official-website#231]
**Is your feature request related to a problem? Please describe.**

the Footer doesn't stay at the bottom when there's not enough content on the page which results in it being in the middle of the screen in some cases. This negatively affects the user experience especially on pages with little content.

-1. The footer is not well aligned with the content
-2.Extra space at the bottom of the footer
-3.Logo icon and heading are not aligned correctly:

**Describe the solution you'd like**
1.Content Alignment:
Adjust the footer’s structure to ensure all elements (text, links, icons) are properly aligned with each other and consistent with the overall page design.

2.Remove Extra Space:
Fix the CSS to remove the extra space beneath the footer so that it sits neatly at the bottom of the page.

3.Logo and Heading Alignment:
Ensure the logo icon and the "Code Social" heading are correctly aligned in a row, with balanced spacing, to improve the visual layout.

**Describe alternatives you've considered**
-Implementing a flexbox or grid layout for the footer to ensure consistent alignment.
-Removing any padding or margin that might be causing the extra space below the footer.

**Additional context**
![Screenshot (463)](https://github.com/user-attachments/assets/b16fae90-a679-4baa-9ee1-11456c059207)

**Comment by MadhavDhatrak** [comment]
@SaurabhS55 @Rizwan102003 @arushi2610 Assign this issue to me under Hacktoberfest and GSSoC-Ext.

**Comment by pulkitpathak99** [comment]
I have assigned this issue to you
