### ISSUE TITLE
Adding chatbot support system✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Code-Social/official-website#269]
@Rizwan102003 
I want to add a chatbot to the website, which will be fine tuned for this website and help you solve user queries. Can you please assign me this  issues?.

**Comment by Rizwan102003** [comment]
@T-Rahul-prabhu-38 I have assigned you. Try to use separate files wherever you can. @SaurabhS55 @pulkitpathak99 please put the labels here.
