### ISSUE TITLE
[Feat]-Add Free Learning Resources Page for Students

### ISSUE THREAD

**Issue by MadhavDhatrak** [Code-Social/official-website#308]
**Is your feature request related to a problem? Please describe.**
Many students in the community are often frustrated because they don’t know where to find free, high-quality learning resources to help them improve their tech skills. New learners frequently ask for recommendations for tutorials, books, and documentation, which makes it difficult to direct them efficiently.

Additionally, the lack of a central location for these resources means that students have to search across multiple platforms, which is time-consuming and overwhelming.

**Describe the solution you'd like**
I would like to add a **Free Learning Resources page** to the community website, where users can find and access tech-related resources in one central place. The page will feature:

1.Categories like web development, programming languages, AI/ML, DevOps, and open-source.
2.Descriptions, difficulty levels, and links for each resource.
3.An option for users to suggest new resources and contribute to keeping the page updated.

**Additional context**
![Screenshot (482)](https://github.com/user-attachments/assets/f76ad860-55af-49ee-9767-c11aaca97033)

**Comment by MadhavDhatrak** [comment]
@SaurabhS55 @pulkitpathak99 @Rizwan102003 Assign this issue to me under Hacktoberfest and GSSoC-Ext.

**Comment by Rizwan102003** [comment]
@MadhavDhatrak I have assigned you. I suggest you to make separate files wherever possible. @SaurabhS55 @pulkitpathak99 please put the labels here.

**Comment by MadhavDhatrak** [comment]
@Rizwan102003 Thanks for assigning me! I will make sure to create separate files
