### ISSUE TITLE
[⭐FEATURE] Add a Translation Tool (all language) ✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Code-Social/official-website#314]
I want to add a Translation Tool(all language) properly.

PA please assign me this task.

![Screenshot 2024-10-20 165825](https://github.com/user-attachments/assets/7dd38f5a-1dc9-4c0e-af00-9f6a643c7bcf)

**Comment by Subhajit-2023-44** [comment]
@SaurabhS55 @pulkitpathak99 @Rizwan102003 PA please assign me

**Comment by Subhajit-2023-44** [comment]
@SaurabhS55 @pulkitpathak99 @Rizwan102003 PA please assign me

**Comment by Subhajit-2023-44** [comment]
@SaurabhS55 @pulkitpathak99 @Rizwan102003 PA please assign me

**Comment by Rizwan102003** [comment]
@Subhajit-2023-44 we will not be needing this feature
