### ISSUE TITLE
Low Contrast Issue in Navigation Menu and Navigation Bars

### ISSUE THREAD

**Issue by Kshitijasharma** [Code-Social/official-website#316]
**Describe the bug**
The website is using a dark background with dark-colored links in the navigation menu. This causes poor visibility for the links, making them difficult to read. For instance, the links like "Meet Our Team," "Join Our Team," etc., are in dark blue, which blends into the background in dark mode.

**To Reproduce**
1. Go to 'Learning'.
2. See error

**Expected behavior**
Proper readability of the text written on navigation bar.

**Screenshots**
<img width="959" alt="issue2" src="https://github.com/user-attachments/assets/cd4d01f1-47c1-408b-8fdf-bfbeb80d7033">

@Rizwan102003

**Comment by Rizwan102003** [comment]
@Kshitijasharma I have assigned you. @SaurabhS55 @pulkitpathak99 please put the labels.
