### ISSUE TITLE
Visibility of title unusally when we open the website and overalapping navbar

### ISSUE THREAD

**Issue by ChetanSingh14** [Code-Social/official-website#322]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when we open the website and usually one dropdown is open and some option are not visible and overlapping the navbar

**Describe the solution you'd like**
update the styling 

**Describe alternatives you've considered**

**Additional context**
<img width="1680" alt="Screenshot 2024-10-21 at 11 16 40 AM" src="https://github.com/user-attachments/assets/65457e65-f413-4f35-8090-d367f2621be9">

<img width="1260" alt="Screenshot 2024-10-21 at 11 19 49 AM" src="https://github.com/user-attachments/assets/277d0535-b289-44bb-a3ac-e56e3c56e6ff">

**Comment by ChetanSingh14** [comment]
@Rizwan102003 please review this issue and assign it to me

**Comment by Rizwan102003** [comment]
@ChetanSingh14 i have assigned you this issue. @SaurabhS55 @pulkitpathak99 please put the labels here

**Comment by ChetanSingh14** [comment]
@Rizwan102003 please review pr 
@SaurabhS55 
@pulkitpathak99

**Comment by ChetanSingh14** [comment]
@Rizwan102003 can i raise issue for better footer and alignment of icon and work on ui of footer .Please assign this to me
