### ISSUE TITLE
appearing icon two time on same page 

### ISSUE THREAD

**Issue by ChetanSingh14** [Code-Social/official-website#324]
**Is your feature request related to a problem? Please describe.**
it does look good and doesnt make any sense either it should be below about us or in footer
<img width="1680" alt="Screenshot 2024-10-21 at 12 02 15 PM" src="https://github.com/user-attachments/assets/818b2ef7-d3dd-47cd-8721-637b4814e1a1">

<img width="1680" alt="Screenshot 2024-10-21 at 12 02 12 PM" src="https://github.com/user-attachments/assets/549b5e09-839b-4976-a247-ca9773db0d93">

**Describe the solution you'd like**
it should be below about us or in footer 

**Describe alternatives you've considered**

**Additional context**

//expectation please provide level 2 contributor
@Rizwan102003 assign this issue to me

**Comment by Naga-Himaja** [comment]
My suggestion would be to keep this in the footer, with About us title. Then, it would be wise to remove the "ABOUT COMMUNITY" section in the starting of the page.

Please assign this issue to me @ChetanSingh14 @Rizwan102003

**Comment by Rizwan102003** [comment]
@Naga-Himaja @ChetanSingh14 we wanted these that way. Please find some other issues to work on.
