### ISSUE TITLE
The icons and content are not aligned properly in footer section of blog.

### ISSUE THREAD

**Issue by Kshitijasharma** [Code-Social/official-website#331]
**Describe the bug**
The icons (WhatsApp, LinkedIn, Discord) and the contents of footer are not aligned properly.

**To Reproduce**
1. Go to 'https://code-social.github.io/official-website/'
2. Click on 'Blogs'
3. Scroll down to the footer of page.

**Expected behavior**
It should be aligned in aesthetic manner such that it could enhance the look of website.

**Screenshots**
<img width="896" alt="issue4" src="https://github.com/user-attachments/assets/07760c18-a6e0-4ed3-90a2-38b93b1ada83">

## Can you assign me this issue?
@Rizwan102003

**Comment by Rizwan102003** [comment]
@Kshitijasharma I have assigned you this issue. @SaurabhS55 @pulkitpathak99 please put the labels here
