### ISSUE TITLE
Enhancement of Learning Page

### ISSUE THREAD

**Issue by aashutosh585** [Code-Social/official-website#332]
hey @Rizwan102003 ,I want to enhance the  learning page of your website. By improving navigation, adding footer in learning page, button for dark/light and also some other changes  . 
       

![Screenshot 2024-10-22 001521](https://github.com/user-attachments/assets/b697d371-a70c-4206-9397-773f314bd162)

Assign me for this work .
Make sure to add Lebels, gssoc-ext, hactoberfest, and level1, level2, level3.

**Comment by Rizwan102003** [comment]
@aashutosh585 I have assigned you this issue. @SaurabhS55 @pulkitpathak99 please put the labels here

**Comment by Shalinis19137** [comment]
I really like your app and want to work on your project ,please assign this issue to me under gssoc-ext 2024
