### ISSUE TITLE
[Doc]: adding Stargazers and Forkers section to readme.md

### ISSUE THREAD

**Issue by amiya-cyber** [Code-Social/official-website#345]
Issue Description
adding Stargazers and Forkers section to readme.md

use case

1. Stargazers highlight the GitHub users' profiles who starred the repository.
2. And forkers show the people who have already forked the repository
![2024-10-22 (11)](https://github.com/user-attachments/assets/3e6ed1fb-1b87-4978-a498-91305a7c2dfc)

**Comment by amiya-cyber** [comment]
please assign me this issue with all the labels 
level 2 or level 3
hacktober fest
gssoc

**Comment by amiya-cyber** [comment]
i had made a pr please @Rizwan102003 assign me and add all the labels
hacktober fest
gssoc ext
level 2 or level 3

**Comment by Rizwan102003** [comment]
Make the readme pr again, i will assign u there. Also, for the stargazers and forkers section, can you make it like the contributors section removing the white background.
