### ISSUE TITLE
Adding "Events" Webpage for Discovering new events

### ISSUE THREAD

**Issue by VidhanThakur09** [Code-Social/official-website#358]
**Is your feature request related to a problem? Please describe.**

The Code Social Community currently lacks a dedicated "Event" webpage, which is crucial for Discovering new events. This absence can lead to confusion or inconsistent member behavior, affecting the website impression .

**Describe the solution you'd like**

I propose creating a dedicated "Events" webpage. The page should be easily accessible through the footer navigation. This page would provide clear visibility for events and reinforce the values that help to  up to date and knowledge of event for user.

**Additional context**

<img width="959" alt="Screenshot 2024-10-23 014915" src="https://github.com/user-attachments/assets/32fa7d3c-ba43-4600-9bb5-c515bf409999">

@pulkitpathak99 @Rizwan102003 @SaurabhS55 can you assign this issue to me with labels "gssoc-ext" and "hacktoberfest-accepted";

**Comment by Rizwan102003** [comment]
@VidhanThakur09  I have assigned you this issue. @pulkitpathak99 @SaurabhS55 please put the labels here

**Comment by VidhanThakur09** [comment]
Thank you for assigning this to me.

**Comment by VidhanThakur09** [comment]
@pulkitpathak99 @SaurabhS55 can you add labels "gssoc-ext" with levels and "hacktoberfest-accepted", so that I can start working on the issue?

**Comment by Rizwan102003** [comment]
@VidhanThakur09 u can start working on the issue and make pr. Don't worry about the labels.

**Comment by VidhanThakur09** [comment]
Ok sir
