### ISSUE TITLE
Restrict Event Creation for Past Dates

### ISSUE THREAD

**Issue by akshayabankumidi** [Code-Social/official-website#365]
Description: Currently, users can create events for past dates on the event calendar. We need to restrict this to ensure that events can only be created for the current or future dates.

![image](https://github.com/user-attachments/assets/164b5db7-83b7-4c1f-aeec-817ec0beeb30)

Expected Behavior: The system should restrict users from selecting past dates and provide a validation message when attempting to create an event for a date before the current date.

Actual Behavior: The system allows users to create events for past dates.

Possible Solution:
Implement date validation to disable event creation for any past dates.

Labels:
Bug
gssoc-ext
hacktoberfest-accepted
level1

Maintainers: @Rizwan102003 @SaurabhS55 Could you please assign this issue to me under Hacktoberfest? I would like to work on it.

**Comment by SaurabhS55** [comment]
@akshayabankumidi I have assigned this issue to you. You can start working on it. make sure to create new branch for you changes. 
Expected result: restrict users from creating events for past dates. (if date is past date then this "add form button should be disabled and restricted"). Don't restrict users from veiwing past created events.

**Comment by akshayabankumidi** [comment]
@SaurabhS55  could u please review my code
