### ISSUE TITLE
Improving the UI of the mentorship page  .

### ISSUE THREAD

**Issue by AADESHak007** [Code-Social/official-website#369]
**Is your feature request related to a problem? Please describe.**
The layout of the mentorship page which depicts all the Core team members need a redesign . 

**Describe the solution you'd like**
The layout of the cards are something that I can work on and adding a background will also help in improving the page  .
I want to work on this issue . Please assign this is issue to me  .
![Screenshot 2024-10-23 145935](https://github.com/user-attachments/assets/4aaca66d-9dfb-4c77-9a61-6321711983b9)

**Comment by Rizwan102003** [comment]
@AADESHak007 i have assigned you. @pulkitpathak99 @SaurabhS55 please put the labels here
