### ISSUE TITLE
missing logo

### ISSUE THREAD

**Issue by Pragati1466** [Code-Social/official-website#374]
**Describe the bug**
The company logo is missing in the footer of the website, leaving an empty space where the logo should be.

**To Reproduce**

Go to the website's homepage.
Scroll down to the footer section.
Notice that the logo does not appear in the designated area.
**Expected behavior**
The company logo should be visible in the footer, properly aligned and displayed across all devices.

**Screenshots**
<img width="1615" alt="Screen Shot 2024-10-24 at 1 52 48 AM" src="https://github.com/user-attachments/assets/a40ff273-93b4-43d2-9036-de9d86e096c9">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pragati1466** [comment]
@Rizwan102003

**Comment by Pragati1466** [comment]
@SaurabhS55 and please add the relevant labels for gssoc

**Comment by Pragati1466** [comment]
@pulkitpathak99

**Comment by pulkitpathak99** [comment]
I have assigned this issue to you!! @Pragati1466

**Comment by Pragati1466** [comment]
ok will solve by tommorow

**Comment by shivhere007** [comment]
If this issue is not solved till now, kindly assign it to me please as i saw the logo is still missing in learning and registration page.
@pulkitpathak99 
![Screenshot 2024-10-25 183323](https://github.com/user-attachments/assets/ac679179-5743-4b8f-a50f-13f59563ad2b)

**Comment by Rizwan102003** [comment]
@Pragati1466 @shivhere007 the logo is currently working

**Comment by Pragati1466** [comment]
@Rizwan102003 but could you please refrence which issue solved it I took the issue first submitted the pr at time then why not accepted and at the time i submitted pr logo was still not there and even when the other person messaged and i submiteed pr befoe that thats violating rules pls see to it

**Comment by Pragati1466** [comment]
I solved this issue 2 days ago and the other person message 16 hours ago that the issue is still not solved then why my pr is not accepted

**Comment by Pragati1466** [comment]
@pulkitpathak99

**Comment by Rizwan102003** [comment]
@Pragati1466 We currently have 5 members assigning the issues and merging the pr's. It may be that an issue got created by 2 different contributors and got assigned to them by different mentors. Kindly provide us the issue numbers in question so that we can look into it and resolve the issue.

**Comment by arushi2610** [comment]
@Pragati1466 there are still a lot of improvements required on the website. You can work on other issues and raise a PR on it.
