### ISSUE TITLE
feat: Adding a nav bar in blogs page

### ISSUE THREAD

**Issue by Naga-Himaja** [Code-Social/official-website#380]
**Is your feature request related to a problem? Please describe.**
The Blogs page does not contain a navbar, and it gets problematic to navigate to main page, thus effecting user experience poorly

**Describe the solution you'd like**
Adding the navbar used in home page, to ensure the consistency across the website. Also, there must be a favicon for the Blogs page

Reviewers: @Rizwan102003 @pulkitpathak99 

![Screenshot 2024-10-24 at 5 20 59 PM](https://github.com/user-attachments/assets/14b3fa73-3baa-4ae7-915f-99bd1eb80d87)

**Comment by Naga-Himaja** [comment]
@Rizwan102003 Can you assign me this issue?

**Comment by Naga-Himaja** [comment]
@pulkitpathak99 Can you added GSSOC and Hacktoberfest labels?

**Comment by Rizwan102003** [comment]
@Naga-Himaja i have assigned you. @SaurabhS55 @pulkitpathak99 please put the labels here.

**Comment by Naga-Himaja** [comment]
As per issue #409, would it make sense to add the navbar to the blogs page now?

**Comment by Rizwan102003** [comment]
@Naga-Himaja no,don't work on it anymore. sorry for the inconvenience caused to your work. feel free to check out other issues to work on.
