### ISSUE TITLE
bug: dark/light mode toggle not working in maintenance page

### ISSUE THREAD

**Issue by Naga-Himaja** [Code-Social/official-website#382]
**Describe the bug**
The dark mode and light mode toggle is working fine in the home page, but in learning page or maintenance page, it is not working.

**To Reproduce**
1. Go to https://code-social.github.io/official-website/
2. Click on dark mode toggle button
3. Now click on Follow Us button
4. It automatically turns into light mode 
5. Now click on dark mode toggle
6. It doesn't turn into dark mode

**Expected behavior**
The page should retain the mode across the wepages

**Screen recordings**

https://github.com/user-attachments/assets/ca11a2d4-a064-4e67-9573-a4eaafbfd97c

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]

**Comment by Naga-Himaja** [comment]
@Rizwan102003 @pulkitpathak99 Please assign me this issue

**Comment by Naga-Himaja** [comment]
@pulkitpathak99 Can you added GSSOC and Hacktoberfest labels?

**Comment by Rizwan102003** [comment]
@Naga-Himaja i have assigned you the issue. @SaurabhS55 @pulkitpathak99 please put the labels here.
