### ISSUE TITLE
Enhance Readme.md file

### ISSUE THREAD

**Issue by souvikpramanikgit** [Code-Social/official-website#39]
Hi,

I’ve been exploring the project and appreciate the work you’ve done so far. I’d like to propose an update to the README.md file. Here are a few ideas I have in mind:

I want to add some animations (icons), change the alignment of text and few more changes...

I believe these updates could enhance user understanding and engagement with the project. If you're open to it, I’d love to contribute.

I’m committed to continually improving the quality of our documentation.

Thank you!

**Comment by arushi2610** [comment]
Sue, go ahead. Make the changes and raise a PR.

**Comment by souvikpramanikgit** [comment]
Add level1

**Comment by souvikpramanikgit** [comment]
@arushi2610 add level 1 and gssocext.
