### ISSUE TITLE
Improve Event Calendar

### ISSUE THREAD

**Issue by amitb0ra** [Code-Social/official-website#390]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when the Event Calendar lacks user-friendly features. now it just simply alerts.

### Describe the solution you'd like
I would like to see improvements in the Event Calendar, such as:
- Better UI/UX for navigating through events.
- More Options
- Instead of Simple Alert, better UI to show event details

### Describe alternatives you've considered
Considered using third-party calendar integrations like Google Calendar or Outlook but prefer to improve the native calendar to maintain consistency within Code Social.

### Additional context
**Please assign me under GSSoC'24 ext and hacktoberfest labels**

**Comment by arushi2610** [comment]
Closing the issue, kindly raise a PR when you're done.
