### ISSUE TITLE
 Add More Resources to Code Social Website

### ISSUE THREAD

**Issue by amitb0ra** [Code-Social/official-website#392]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when the list of resources on the Code Social website feels limited and lacks variety in educational content, tools, or relevant links that could help the community.

### Describe the solution you'd like
I would like to see the addition of more resources, including:
- New links to tutorials, articles, and guides.
- Resources categorized by topics such as development, design, open-source, etc.
- Tools and libraries that would benefit community members.
- Additional sections for podcasts, videos, and interactive learning platforms.

### Describe alternatives you've considered
I've considered recommending third-party resource websites, but enhancing the current resources section on the official website would provide more direct value to the community.

### Additional context
**Please assign me under GSSoC'24 ext and hacktoberfest labels**

**Comment by arushi2610** [comment]
Closing the issue, kindly raise a PR when you're done.
