### ISSUE TITLE
Add Peer-to-Peer Sessions to Code Social Website

### ISSUE THREAD

**Issue by amitb0ra** [Code-Social/official-website#394]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when there are limited opportunities for community members to engage in peer-to-peer learning and collaboration on the Code Social website.

### Describe the solution you'd like
I would like to see a section for organizing peer-to-peer sessions where members can:
- Schedule sessions to collaborate on coding projects, design, or other skills.
- Participate in study groups or pair programming sessions.
- Engage in open discussions to share knowledge and help each other improve.
- Create recurring peer-to-peer events on specific topics like technology trends or community-building strategies.

### Describe alternatives you've considered
I've considered using external platforms for organizing peer-to-peer learning, but having an integrated solution within Code Social would foster a stronger sense of community and collaboration.

### Additional context
**Please assign me under GSSoC'24 ext and hacktoberfest labels**

**Comment by arushi2610** [comment]
This can be done through our [Discord server](bio.link/codesocial). Kindly see it and let me know what different you are planning to integrate on the website.

**Comment by amitb0ra** [comment]
> This can be done through our [Discord server](bio.link/codesocial). Kindly see it and let me know what different you are planning to integrate on the website.

like we can update vcs or sessions link into it. so that newbies as they are not familiar with discord UI can join session more easily 

also not only discord, if session happens in gmeet or anything else there will be a central page for that
