### ISSUE TITLE
Re-design the Free Learning Resources Page

### ISSUE THREAD

**Issue by achintyasrivastav** [Code-Social/official-website#399]
🔴 Title : Enhancement of Free Learning Resources Page

🔴 Enhancement Aim : To make the website look cooler and more engaging.

🔴 Changes :   -Update the layout to be more visually appealing and user-friendly.
                        -Implement a modern color scheme that aligns with the travel theme.
                        -Introduce new fonts for better readability and a fresh look.
                        -Ensure the design is fully responsive for mobile devices.

Please label this request under Hacktoberfest 2024 and Girlscript Summer of Code 2024.

**Comment by arushi2610** [comment]
Closing the issue, kindly raise a PR when you're done.
