### ISSUE TITLE
there is no scroll up button at the landing page 

### ISSUE THREAD

**Issue by 2004pra** [Code-Social/official-website#405]
allow me to add the scroll up button over the landing by doing some major changes like css and javscript 
please assign me this under gssoc extd 24, hactober fest , please make it level 2 please  mam .....
@arushi2610

**Comment by arushi2610** [comment]
Closing the issue, kindly raise a PR when you're done.

**Comment by 2004pra** [comment]
why 
so i should do it without getting assigned

**Comment by 2004pra** [comment]
whatever i am raising the pr

**Comment by Wahid7852** [comment]
@arushi2610 I believe this Issue was closed by mistake. Kindly revert

**Comment by techy4shri** [comment]
@arushi2610 you do not close an issue when you want someone to work on it. Kindly assign @2004pra and open this issue again. Otherwise it will not be counted.
