### ISSUE TITLE
remove BLOGS section

### ISSUE THREAD

**Issue by Rizwan102003** [Code-Social/official-website#409]
**We at Code Social have decided we will not be needing a BLOGS section in the official website for the time-being and would like to remove the section altogether**

**Remove the BLOGS website html,css and other related files. Remove the BLOGS section from the navbar of home page and all the other pages.**

**Additionally - shift the "live events" in the navbar to the right a little **

***We will be assigning issues on a first come - first serve basis.***

**Comment by 1-SubhamSingh** [comment]
Hey , can you assigm me this ?

**Comment by Rizwan102003** [comment]
@1-SubhamSingh I have assigned you this issue . after you finish, attach a screenshot here so that we can check before merging the pr. Additionally ,I shall be giving you 24 hours to fix the issue and create a pr, after which this issue will be assigned to the next contributor. Best of luck.

**Comment by 1-SubhamSingh** [comment]
@Rizwan102003 I have done the changes and attached the screenshots , you can check and merge the PR.
