### ISSUE TITLE
enhancement: creating a separate html page for navbar and footer

### ISSUE THREAD

**Issue by Naga-Himaja** [Code-Social/official-website#413]
**Problem**
The navbar is being enhanced by many contributors, and it is different on each page. It is not consistent across the website, and might effect user experience

**Solution**
Creating separate pages for navbar and footer, and loading those in each page using js

Reviewers: @arushi2610 @pulkitpathak99 @Rizwan102003

**Comment by Naga-Himaja** [comment]
@arushi2610 @pulkitpathak99 @Rizwan102003 Please assign me this issue

**Comment by SaurabhS55** [comment]
@Naga-Himaja As your contribution might impact on all pages. so **make sure to create new branch for your changes**.
if you have any doubt then feel free to ask us.

**Comment by Naga-Himaja** [comment]
> @Naga-Himaja As your contribution might impact on all pages. so **make sure to create new branch for your changes**. if you have any doubt then feel free to ask us.

Thank you for the reminder! I make sure to create a new branch for every change to maintain clarity in my pull requests. I'll definitely reach out if I have any questions.
