### ISSUE TITLE
Add a pop up dialog box for subscribing to newsletter ✨✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Code-Social/official-website#415]
I want to add a pop up dialog box for subscribing to newsletter..

PA please assign me for this task..

**Comment by Subhajit-2023-44** [comment]
@SaurabhS55 @pulkitpathak99 @Rizwan102003 PA please assign me

**Comment by Rizwan102003** [comment]
@Subhajit-2023-44 we do not have a community newsletter so we will not be needing this
