### ISSUE TITLE
Chatbot Icon overlaps with Scroll to top button 

### ISSUE THREAD

**Issue by sezallagwal** [Code-Social/official-website#421]
**Describe the bug**
![image](https://github.com/user-attachments/assets/cf9b95a9-d953-484c-bc69-609213321fb8)
scroll to top button is hiding behind chatbot icon
I want to fix this @Rizwan102003 
please assign this under `gssoc-ext` and `hacktoberfest`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Rizwan102003** [comment]
this issue is already being worked on by others. if they fail,we will reasign to you.

**Comment by sezallagwal** [comment]
okay cool
