### ISSUE TITLE
[Feat]-Add Structured Content to "Join Our Team" Page

### ISSUE THREAD

**Issue by MadhavDhatrak** [Code-Social/official-website#431]
**Is your feature request related to a problem? Please describe.**
Currently, the "Join Our Team" page is empty, which could be confusing for users visiting the page with an interest in joining the community. A blank or underdeveloped page may lead to missed engagement opportunities and a lack of clarity on the process for becoming a part of the team.

**Describe the solution you'd like**
The "Join Our Team" page should include structured content that effectively introduces the community and explains the benefits and process of joining. This can be broken down as follows:

1.Introduction: Brief overview of the community’s mission, values, and goals.
2.Roles Section: List of open positions with descriptions of each role and necessary skills.
3.Benefits: Details on the advantages of joining, such as skill-building opportunities, networking, and mentorship.
4.Application Process: Clear steps for applying, with an indication of what happens after submission.
5.CTA Button and Contact Info: Prominent “Apply Now” button linking to an application form, and contact details for inquiries.

**Additional context**
![Screenshot (487)](https://github.com/user-attachments/assets/0e10da40-eb1d-40ea-97cc-06c7faabaaf7)

**Comment by MadhavDhatrak** [comment]
@SaurabhS55 @pulkitpathak99 @Rizwan102003 Assign this issue to me under Hactoberfest and GSSoc-Ext

**Comment by Rizwan102003** [comment]
@MadhavDhatrak the join our team button should simply redirect to a g-form. @arushi2610 can provide you with the link.

**Comment by arushi2610** [comment]
Here's the link: https://forms.gle/zDakdQL8ixrVusUU9
