### ISSUE TITLE
Adding a page for the top contributors

### ISSUE THREAD

**Issue by KrishPatel1205** [Code-Social/official-website#454]
**Is your feature request related to a problem? Please describe.**
When the user clicks on the team option they are greeted with cards of non existent people, instead this can be changed in order to display the top contributors of the website.

**Describe the solution you'd like**
Adding a new page to display the top constitutors to the repository along with the number of commits they have made in the order of most commits made to least.

**Comment by KrishPatel1205** [comment]
If this feature is required, if so please assign it to me so that I can start working on it

**Comment by arushi2610** [comment]
Team page is to showcase team members and their information. Contributors are mentioned on the repo, not the website. Thank you for the suggestion; this feature isn't required.
