### ISSUE TITLE
change github icon

### ISSUE THREAD

**Issue by Rizwan102003** [Code-Social/official-website#459]
The current github link icon against a black circle becomes nearly invisible against the dark theme. We basically want the github logo to show against a whiter circular frame so that its easier to see in the website.

**Additional context**
We will assign this issue on a first come-first serve basis. Contributors(if assigned) will be allotted 24hrs to successfully raise a pr and attach a screenshot of their changes for the mentors to see before merging. If any contributor ,after being assigned ,fails to finish the work, the issue will be reassigned to the next contributor .

**Comment by Naga-Himaja** [comment]
Hello @Rizwan102003,
Can you assign this issue to me?
