### ISSUE TITLE
learning page dosen't have scroll to top button

### ISSUE THREAD

**Issue by 2004pra** [Code-Social/official-website#461]
please assign me this issue under gssoc extd , hacktober fest 
and make it atleast level2 
i will also add the scroll to top button at other pages which comes under learning page

**Comment by arushi2610** [comment]
@SaurabhS55 @pulkitpathak99 Please check which level should be assigned.

**Comment by SaurabhS55** [comment]
@2004pra you can start working on this. Make sure to create new branch for your changes.
Don't worry about levels. If you have any doubt then feel free to ask.

**Comment by 2004pra** [comment]
Ok sir

**Comment by Shalinis19137** [comment]
I really like your app and want to work on your project ,please assign this issue to me under gssoc-ext 2024
