### ISSUE TITLE
The scroll to top button and chat bot are coinciding

### ISSUE THREAD

**Issue by laxmikandivalasa** [Code-Social/official-website#466]
**Describe the bug**

The scroll to top button and chat bot are coinciding which make user unattractive
**To Reproduce**
adjust the positioning and z-index properties of both elements in  CSS

**Expected behavior**
 Place the "Scroll to Top" button in a different corner or with slight offsets to avoid the overlap.
**Screenshots**
![Screenshot 2024-10-30 134227](https://github.com/user-attachments/assets/1c9577a1-26e7-4f0e-803e-59620b88db87)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]one plus nord ce 4
 - Browser [e.g. stock browser, safari] chrome

**Additional context**

I'd like to work on this
can you assign this to me

**Comment by arushi2610** [comment]
Approved, Raise a PR when you're done.

**Comment by laxmikandivalasa** [comment]
I've raised the pr #488 
you check it!!
@arushi2610
