### ISSUE TITLE
Navbar and hamburger menu

### ISSUE THREAD

**Issue by Hemraj-7** [Code-Social/official-website#467]
**Describe the bug**
In the navbar when we in the light mode then the list items ( menu ) don't showing. and in the mobile phone hamburger menu don't showing. and also in the mobile phone code-social logo is too big.

**Expected behavior**
I want to do the menu and hamburger menu visible and make the navbar responsive, attractive and user friendly.

**Screenshots**
![Screenshot 2024-10-30 134417](https://github.com/user-attachments/assets/b9bbb3eb-4f9d-4a2b-a5de-f1345089dbc2)
![Screenshot 2024-10-30 134445](https://github.com/user-attachments/assets/9eb355f7-f203-4e1a-983d-9d7770344c0c)

**Desktop (please complete the following information):**
 - Browser [chrome and Brave]

**Smartphone (please complete the following information):**
 - Browser [chrome and Brave]

Assign me this issue with level2 label, I want to work on this issue
Thank you

**Comment by arushi2610** [comment]
This issue has already been assigned to someone else. You can work on other issues. Thanks!
