### ISSUE TITLE
Creating a Join Our Community Page

### ISSUE THREAD

**Issue by VidhanThakur09** [Code-Social/official-website#477]
# **Is your feature request related to a problem? Please describe.**
This issue propose creating a dedicated "Join Our Community" page on the website to encourage user engagement and foster a sense of belonging within our community.

# **Describe the solution you'd like**
## **Use Case:**

- **New User Onboarding:** A clear and inviting landing page for newcomers to learn about the community, its values, and how to get involved.

- **Enhanced User Experience:** A streamlined process for users to connect with other members,

## **Benefits:**

- **Increased Community Engagement:** By providing a dedicated space for community interaction, we can expect higher levels of participation and collaboration.

- **Improved User Retention:** A strong sense of community can lead to increased user loyalty and retention.

- **Enhanced Brand Reputation:** A vibrant and active community can positively impact the brand's reputation and attract new users.

**Additional context**
@arushi2610 @pulkitpathak99 @Rizwan102003 @SaurabhS55 can you assign this issue to me with labels "gssoc-ext" with levels and "hacktoberfest-accepted";

**Comment by Rizwan102003** [comment]
issue already being worked on by another contributer. Please find another issue to work on.

**Comment by VidhanThakur09** [comment]
If the contributor has not completed this issue, could you please assign it to me?

Thank you for your time and consideration.

**Comment by Rizwan102003** [comment]
sure,if the other contributor fails,it would be reassigned to you

**Comment by VidhanThakur09** [comment]
It would be wonderful.
