### ISSUE TITLE
Improving navbar buttons hover

### ISSUE THREAD

**Issue by Sourabh782** [Code-Social/official-website#478]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/ff6d4d32-3eb6-455f-a4bc-2c261872e626)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by arushi2610** [comment]
Kindly raise a PR when you're done.
