### ISSUE TITLE
The Home page and Navbar look so sus i wanted to fix it

### ISSUE THREAD

**Issue by Aayush-Roy** [Code-Social/official-website#48]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Aayush-Roy** [comment]
I would like to work on it, assignn it to me

**Comment by arushi2610** [comment]
Please describe the issue. You can raise a issue when there's proper description of the issue.
