### ISSUE TITLE
Add a User Profiles page 🌟🌟🌟

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Code-Social/official-website#489]
👤✨ I want to create a normal user profile page and a profile icon in the home page navbar that redirects to the profile page...

PA please assign me for this task...

**Comment by Subhajit-2023-44** [comment]
@SaurabhS55 @pulkitpathak99 @Rizwan102003 PA please assign me

**Comment by Rizwan102003** [comment]
@Subhajit-2023-44 we do not need this feature currently. Please find any other issue to work on.
