### ISSUE TITLE
Want to remove 2 ( Follow us ) options in header

### ISSUE THREAD

**Issue by Jivan052** [Code-Social/official-website#495]
**Describe the bug**
In header section of website, there is extra feature of follow us. One in about us section and another is beside about us.

**To Reproduce**
1. Go to 'Website'
2. Click on ' about us in header'
3. You can see that there is 2 options of follow us

**Expected behavior**
It's a good practice to have one "follow us" option in about us feature or it should have seperate section.

**Screenshots**
![image](https://github.com/user-attachments/assets/cb2a79ef-d356-4894-98ea-205fc3aa5cf0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I will remove that bug or extra feature and make it more user friendly.

**Comment by Jivanjamadar** [comment]
@Rizwan102003 assign this issue to me

**Comment by Jivanjamadar** [comment]
@Rizwan102003 any update cause it's almost 3 days.

**Comment by Rizwan102003** [comment]
Please remove the one in navbar and keep the one under about us

**Comment by Jivanjamadar** [comment]
Sure. Will do that.

**Comment by Jivanjamadar** [comment]
@Rizwan102003 can you please review the PR?
