### ISSUE TITLE
Migrate the existing code to React.

### ISSUE THREAD

**Issue by Vaibhav-Kumar-K-R** [Code-Social/official-website#8]
**Is your feature request related to a problem? Please describe.**
Currently we have only html ,css and js.
**Describe the solution you'd like**
Migrate to reacting will make the code base easy to maintain modular.

**Comment by tarunkumar2005** [comment]
I would like to contribute into this. Assign me under GSSOC'24 extd and hacktoberfest'24.

**Comment by samkitsamsukha** [comment]
I would like to contribute by migrating the code base to react, I have experience working with react. 
I could also  reform the ui using tailwindcss along with mobile responsiveness.

**Comment by Rizwan102003** [comment]
Currently, we will not be using react. We will only be using html,css and js.
