### ISSUE TITLE
fixing the UI 

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Code-Social/official-website#98]
can you assign me so i can work on this.
<img width="1463" alt="Screenshot 2024-10-08 at 9 54 05 PM" src="https://github.com/user-attachments/assets/a372b1ee-ab90-45ea-b403-71dfdde0f4fc">

**Comment by SaurabhS55** [comment]
@T-Rahul-prabhu-38 this bug has been resolved. You can find more features to work on.
